"""add wellbore.npdid_wellbore for source provenance

Revision ID: 815f8c6c6353
Revises: b7db30f05a95
Create Date: 2026-09-24 20:03:48.013194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815f8c6c6353'
down_revision: Union[str, None] = 'b7db30f05a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellbores', sa.Column('npdid_wellbore', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_wellbores_name'), 'wellbores', ['name'], unique=False)
    op.create_index(op.f('ix_wellbores_npdid_wellbore'), 'wellbores', ['npdid_wellbore'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wellbores_npdid_wellbore'), table_name='wellbores')
    op.drop_index(op.f('ix_wellbores_name'), table_name='wellbores')
    op.drop_column('wellbores', 'npdid_wellbore')
    # ### end Alembic commands ###
