"""extend events for structured historical drilling-event layer

Revision ID: 84855f85f8ac
Revises: d8d2a40841b4
Create Date: 2026-09-25 23:52:48.209797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84855f85f8ac'
down_revision: Union[str, None] = 'd8d2a40841b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted: the enum TYPE
    # must be created before a column can use it (autogenerate emits the
    # add_column alone, which fails against a fresh DB). ###
    event_severity = postgresql.ENUM("LOW", "MEDIUM", "HIGH", "CRITICAL", name="event_severity")
    event_severity.create(op.get_bind(), checkfirst=True)

    op.add_column('events', sa.Column('severity', event_severity, nullable=True))
    op.add_column('events', sa.Column('source', sa.String(length=64), nullable=False))
    op.add_column('events', sa.Column('source_event_id', sa.String(length=128), nullable=True))
    op.add_column('events', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_events_source_event_id'), 'events', ['source_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_source_event_id'), table_name='events')
    op.drop_column('events', 'extra_metadata')
    op.drop_column('events', 'source_event_id')
    op.drop_column('events', 'source')
    op.drop_column('events', 'severity')

    postgresql.ENUM(name="event_severity").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
