"""initial schema: wells, wellbores, events, source_documents

Revision ID: b7db30f05a95
Revises: 
Create Date: 2026-09-24 19:43:46.112869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'b7db30f05a95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('wells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('well_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('operator', sa.String(length=256), nullable=True),
    sa.Column('field', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('water_depth_m', sa.Float(), nullable=True),
    sa.Column('total_depth_md_m', sa.Float(), nullable=True),
    sa.Column('total_depth_tvd_m', sa.Float(), nullable=True),
    sa.Column('formation', sa.String(length=256), nullable=True),
    sa.Column('spud_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_wells_location', 'wells', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_wells_well_id'), 'wells', ['well_id'], unique=True)
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('well_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('doc_type', sa.Enum('DAILY_REPORT', 'END_OF_WELL_REPORT', 'COMPLETION_REPORT', 'OTHER', name='document_type'), nullable=False),
    sa.Column('uri', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('ocr_applied', sa.Boolean(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_well_id'), 'source_documents', ['well_id'], unique=False)
    op.create_geospatial_table('wellbores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('well_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('trajectory', Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('md_top_m', sa.Float(), nullable=True),
    sa.Column('md_bottom_m', sa.Float(), nullable=True),
    sa.Column('tvd_bottom_m', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_wellbores_trajectory', 'wellbores', ['trajectory'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_wellbores_well_id'), 'wellbores', ['well_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('well_id', sa.UUID(), nullable=False),
    sa.Column('wellbore_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('STUCK_PIPE', 'LOST_CIRCULATION', 'KICK_INFLUX', 'WELLBORE_INSTABILITY', 'BHA_EQUIPMENT_ISSUE', 'NPT', 'OTHER', name='event_type'), nullable=False),
    sa.Column('depth_md_m', sa.Float(), nullable=True),
    sa.Column('depth_tvd_m', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_location', sa.String(length=256), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wellbore_id'], ['wellbores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_source_document_id'), 'events', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_events_well_id'), 'events', ['well_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_well_id'), table_name='events')
    op.drop_index(op.f('ix_events_source_document_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_wellbores_well_id'), table_name='wellbores')
    op.drop_geospatial_index('idx_wellbores_trajectory', table_name='wellbores', postgresql_using='gist', column_name='trajectory')
    op.drop_geospatial_table('wellbores')
    op.drop_index(op.f('ix_source_documents_well_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_wells_well_id'), table_name='wells')
    op.drop_geospatial_index('idx_wells_location', table_name='wells', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('wells')
    # ### end Alembic commands ###
