"""add wellbore.volve_source_id for volve provenance

Revision ID: d8d2a40841b4
Revises: 815f8c6c6353
Create Date: 2026-09-24 22:54:24.414882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d2a40841b4'
down_revision: Union[str, None] = '815f8c6c6353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellbores', sa.Column('volve_source_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellbores', 'volve_source_id')
    # ### end Alembic commands ###
